"""ltemplify / write_moltemplate and the small formatting helpers."""

import molpy as mp
from molpy.parser.moltemplate.lt_writer import (
    _fmt,
    _is_synthetic,
    _sanitise_id,
    ltemplify,
    write_moltemplate,
)


def _water():
    mol = mp.Atomistic()
    o = mol.def_atom(
        name="O", element="O", type="OW", charge=-0.834, x=0.0, y=0.0, z=0.0
    )
    h = mol.def_atom(
        name="H1", element="H", type="HW", charge=0.417, x=0.96, y=0.0, z=0.0
    )
    mol.def_bond(o, h, type="OW-HW")
    ff = mp.ForceField(name="tip3p", units="real")
    atoms = ff.def_atomstyle("full")
    ow = atoms.def_type("OW", mass=15.999, charge=-0.834)
    hw = atoms.def_type("HW", mass=1.008, charge=0.417)
    ff.def_bondstyle("harmonic").def_type(ow, hw, k=450.0, r0=0.9572)
    return mol, ff


def test_fmt_is_compact_but_unambiguous():
    assert _fmt(1.0) == "1"
    assert _fmt(0.9572) == "0.9572"
    assert _fmt(1e-5) == "1.000000e-05"
    assert _fmt(12345678.0) == "1.234568e+07"
    assert _fmt("text") == "text"


def test_sanitise_id_keeps_identifier_characters_only():
    assert _sanitise_id("C1") == "C1"
    assert _sanitise_id("C 1$") == "C_1_"
    assert _sanitise_id("") == "x"


def test_synthetic_names_carry_an_endpoint_suffix():
    assert _is_synthetic("CT_i") and _is_synthetic("x_l")
    assert not _is_synthetic("CT")


def test_ltemplify_renders_masses_charges_atoms_and_bonds():
    mol, ff = _water()
    text = ltemplify(mol, ff, class_name="Water")
    assert text.startswith("# Auto-generated by MolPy ltemplify.")
    assert 'write_once("Data Masses")' in text and "@atom:OW 15.999" in text
    assert "set type @atom:OW charge -0.834" in text
    assert 'write("Data Atoms")' in text and "@atom:HW 0.417 0.96 0 0" in text
    assert 'write("Data Bonds")' in text
    assert text.rstrip().endswith("sys = new Water")


def test_write_moltemplate_creates_parents_and_returns_the_path(tmp_path):
    mol, ff = _water()
    out = write_moltemplate(mol, ff, tmp_path / "nested" / "water.lt")
    assert out == (tmp_path / "nested" / "water.lt").resolve()
    assert "Data Atoms" in out.read_text()
