"""Serialise a MolPy ``(Atomistic, ForceField)`` pair back into a ``.lt`` file.

The output is a MolPy-to-moltemplate "ltemplify" — the inverse of
``read_moltemplate_system``. It emits a single moltemplate class that
contains every atom, bond, angle, dihedral and improper from the given
``Atomistic``, plus ``Data Masses`` / ``In Charges`` / ``In Settings``
blocks derived from the ``ForceField``.

Limitations:
    * Every atom is dumped into one flat class — we do not attempt to
      recover a class hierarchy from a pre-merged system.
    * ``By Type`` wildcards and ``replace{}`` directives are not emitted;
      each bond / angle / … gets its concrete ``@bond:…`` type.
    * Comments and whitespace from the original ``.lt`` (if any) are lost.

Round-tripping ``read_moltemplate_system → write_moltemplate`` produces
a ``.lt`` file that, when re-read, yields an equivalent ``Atomistic``
with identical atom/bond/angle/dihedral/improper counts.
"""

from __future__ import annotations

import math
from pathlib import Path

from molpy.core.atomistic import Atomistic
from molpy.parser.moltemplate.builder import _DEGREE_PARAMS, _PARAM_NAMES
from molpy.core.forcefield import (
    AngleStyle,
    AngleType,
    AtomStyle,
    AtomType,
    BondStyle,
    BondType,
    DihedralStyle,
    DihedralType,
    ForceField,
    ImproperStyle,
    ImproperType,
    PairStyle,
    PairType,
)


def write_moltemplate(
    atomistic: Atomistic,
    ff: ForceField,
    dest: str | Path,
    *,
    class_name: str = "System",
) -> Path:
    """Write an ``Atomistic`` + ``ForceField`` pair as a moltemplate ``.lt``.

    Args:
        atomistic: The system to serialise.
        ff: The force field to serialise.
        dest: Output ``.lt`` path (parent directories are created).
        class_name: Name of the emitted moltemplate class.

    Returns:
        The resolved output path.
    """
    text = ltemplify(atomistic, ff, class_name=class_name)
    dest_path = Path(dest)
    dest_path.parent.mkdir(parents=True, exist_ok=True)
    dest_path.write_text(text, encoding="utf-8")
    return dest_path.resolve()


def ltemplify(
    atomistic: Atomistic,
    ff: ForceField,
    *,
    class_name: str = "System",
) -> str:
    """Return the moltemplate-style ``.lt`` representation of ``(atomistic, ff)``."""
    lines: list[str] = [
        f"# Auto-generated by MolPy ltemplify.",
        f"",
        f"{class_name} {{",
    ]

    lines.extend(_render_data_masses(ff))
    lines.extend(_render_data_charges(ff))
    lines.extend(_render_in_settings(ff))
    lines.extend(_render_data_atoms(atomistic))
    lines.extend(_render_data_bonds(atomistic))
    lines.extend(_render_data_angles(atomistic))
    lines.extend(_render_data_dihedrals(atomistic))
    lines.extend(_render_data_impropers(atomistic))

    lines.append(f"}} # {class_name}")
    lines.append("")
    lines.append(f"sys = new {class_name}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Force-field blocks
# ---------------------------------------------------------------------------


def _render_data_masses(ff: ForceField) -> list[str]:
    atom_types = [t for t in _collect_atomtypes(ff) if not _is_synthetic(t.name)]
    if not atom_types:
        return []
    lines = ['  write_once("Data Masses") {']
    for at in atom_types:
        mass = at["mass"]
        lines.append(f"    @atom:{at.name} {_fmt(mass)}")
    lines.append("  }")
    lines.append("")
    return lines


def _render_data_charges(ff: ForceField) -> list[str]:
    atom_types = [
        t
        for t in _collect_atomtypes(ff)
        if t.get("charge") and not _is_synthetic(t.name)
    ]
    if not atom_types:
        return []
    lines = ['  write_once("In Charges") {']
    for at in atom_types:
        lines.append(f"    set type @atom:{at.name} charge {_fmt(at['charge'])}")
    lines.append("  }")
    lines.append("")
    return lines


def _is_synthetic(name: str) -> bool:
    """True if ``name`` is a builder-synthesised placeholder (``foo_i``/``_j``/…)."""
    return name.endswith(("_i", "_j", "_k", "_l"))


def _render_in_settings(ff: ForceField) -> list[str]:
    lines: list[str] = ['  write_once("In Settings") {']
    any_line = False
    for style in ff.get_styles(PairStyle):
        for pt in style.get_types(PairType):
            toks = _pair_coeff_tokens(pt)
            if toks is None:
                continue
            lines.append(
                f"    pair_coeff @atom:{pt.itom.name} @atom:{pt.jtom.name} "
                f"{style.name} {toks}"
            )
            any_line = True
    for style in ff.get_styles(BondStyle):
        for bt in style.get_types(BondType):
            params = _param_tokens(bt, "bond", style.name)
            if params is None:
                continue
            lines.append(f"    bond_coeff @bond:{bt.name} {style.name} {params}")
            any_line = True
    for style in ff.get_styles(AngleStyle):
        for at in style.get_types(AngleType):
            params = _param_tokens(at, "angle", style.name)
            if params is None:
                continue
            lines.append(f"    angle_coeff @angle:{at.name} {style.name} {params}")
            any_line = True
    for style in ff.get_styles(DihedralStyle):
        for dt in style.get_types(DihedralType):
            params = _param_tokens(dt, "dihedral", style.name)
            if params is None:
                continue
            lines.append(
                f"    dihedral_coeff @dihedral:{dt.name} {style.name} {params}"
            )
            any_line = True
    for style in ff.get_styles(ImproperStyle):
        for it in style.get_types(ImproperType):
            params = _param_tokens(it, "improper", style.name)
            if params is None:
                continue
            lines.append(
                f"    improper_coeff @improper:{it.name} {style.name} {params}"
            )
            any_line = True
    if not any_line:
        return []
    lines.append("  }")
    lines.append("")
    return lines


def _pair_coeff_tokens(pt) -> str | None:
    kwargs = getattr(pt.params, "kwargs", {})
    eps = kwargs.get("epsilon")
    sig = kwargs.get("sigma")
    if eps is None or sig is None:
        return None
    return f"{_fmt(eps)} {_fmt(sig)}"


def _to_file_units(name: str, value: float) -> float:
    """Undo the reader's normalization: reference angles are degrees in a file."""
    return math.degrees(value) if name in _DEGREE_PARAMS else value


def _param_tokens(t, kind: str, style_name: str) -> str | None:
    """Render a ``Type`` object's numeric parameters in ``*_coeff`` order.

    A ``*_coeff`` line is positional, so the order is the reader's own
    ``_PARAM_NAMES`` table read backwards — one table, both directions, so a
    rename cannot desynchronize them. The canonical names carry no positional
    information of their own (``sign`` precedes ``periodicity`` for ``cvff`` and
    follows it nowhere else), which is exactly why guessing an order from the
    key names is not safe. Styles with no table fall back to the historical
    best-effort ordering.
    """
    kwargs = dict(getattr(t.params, "kwargs", {}))
    names = _PARAM_NAMES.get((kind, style_name))
    if names is not None:
        values = [kwargs.get(n) for n in names]
        missing = [n for n, v in zip(names, values, strict=True) if v is None]
        if missing:
            # A positional line with a hole is not a shorter line, it is a wrong
            # one: every later value shifts into the missing slot's meaning.
            raise ValueError(
                f"{kind}_coeff for style '{style_name}' type "
                f"'{getattr(t, 'name', '?')}' is missing {missing}; "
                f"'{style_name}' takes {list(names)} in that order"
            )
        return " ".join(
            _fmt(_to_file_units(n, float(v)))
            for n, v in zip(names, values, strict=True)
        )

    preferred_order = (
        "k",
        "r0",
        "k2",
        "k3",
        "k4",
        "theta0",
        "chi0",
        "ub",
        "k1",
        "k2",
        "k3",
        "k4",
        "periodicity",
        "phase",
        "sign",
        "weight",
        "epsilon",
        "sigma",
    )
    remaining = set(kwargs) - {"name", "itom", "jtom", "ktom", "ltom"}
    order: list[str] = []
    for k in preferred_order:
        if k in remaining:
            order.append(k)
            remaining.discard(k)
    order.extend(sorted(remaining))
    parts: list[str] = []
    for k in order:
        v = kwargs.get(k)
        if v is None:
            continue
        try:
            parts.append(_fmt(_to_file_units(k, float(v))))
        except (TypeError, ValueError):
            continue
    return " ".join(parts) if parts else None


# ---------------------------------------------------------------------------
# Topology blocks
# ---------------------------------------------------------------------------


def _render_data_atoms(atomistic: Atomistic) -> list[str]:
    atoms = list(atomistic.atoms)
    if not atoms:
        return []
    names = _atom_name_map(atomistic)
    lines = ['  write("Data Atoms") {']
    for atom in atoms:
        aid = names[id(atom)]
        atype = atom["type"]
        charge = float(atom["charge"])
        x = float(atom["x"])
        y = float(atom["y"])
        z = float(atom["z"])
        lines.append(
            f"    $atom:{aid} $mol:. @atom:{atype} {_fmt(charge)} "
            f"{_fmt(x)} {_fmt(y)} {_fmt(z)}"
        )
    lines.append("  }")
    lines.append("")
    return lines


def _render_data_bonds(atomistic: Atomistic) -> list[str]:
    bonds = list(atomistic.bonds)
    if not bonds:
        return []
    names = _atom_name_map(atomistic)
    lines = ['  write("Data Bonds") {']
    for i, bond in enumerate(bonds, start=1):
        btype = bond.get("type") or "unknown"
        lines.append(
            f"    $bond:b{i} @bond:{btype} "
            f"$atom:{names[id(bond.itom)]} $atom:{names[id(bond.jtom)]}"
        )
    lines.append("  }")
    lines.append("")
    return lines


def _render_data_angles(atomistic: Atomistic) -> list[str]:
    angles = list(atomistic.angles)
    if not angles:
        return []
    names = _atom_name_map(atomistic)
    lines = ['  write("Data Angles") {']
    for i, ang in enumerate(angles, start=1):
        atype = ang.get("type") or "unknown"
        lines.append(
            f"    $angle:a{i} @angle:{atype} "
            f"$atom:{names[id(ang.itom)]} "
            f"$atom:{names[id(ang.jtom)]} "
            f"$atom:{names[id(ang.ktom)]}"
        )
    lines.append("  }")
    lines.append("")
    return lines


def _render_data_dihedrals(atomistic: Atomistic) -> list[str]:
    dihes = list(atomistic.dihedrals)
    if not dihes:
        return []
    names = _atom_name_map(atomistic)
    lines = ['  write("Data Dihedrals") {']
    for i, d in enumerate(dihes, start=1):
        dtype = d.get("type") or "unknown"
        lines.append(
            f"    $dihedral:d{i} @dihedral:{dtype} "
            f"$atom:{names[id(d.itom)]} "
            f"$atom:{names[id(d.jtom)]} "
            f"$atom:{names[id(d.ktom)]} "
            f"$atom:{names[id(d.ltom)]}"
        )
    lines.append("  }")
    lines.append("")
    return lines


def _render_data_impropers(atomistic: Atomistic) -> list[str]:
    imprs = list(atomistic.impropers)
    if not imprs:
        return []
    names = _atom_name_map(atomistic)
    lines = ['  write("Data Impropers") {']
    for i, d in enumerate(imprs, start=1):
        itype = d.get("type") or "unknown"
        lines.append(
            f"    $improper:i{i} @improper:{itype} "
            f"$atom:{names[id(d.itom)]} "
            f"$atom:{names[id(d.jtom)]} "
            f"$atom:{names[id(d.ktom)]} "
            f"$atom:{names[id(d.ltom)]}"
        )
    lines.append("  }")
    lines.append("")
    return lines


# ---------------------------------------------------------------------------
# Utility helpers
# ---------------------------------------------------------------------------


def _collect_atomtypes(ff: ForceField) -> list[AtomType]:
    seen: dict[str, AtomType] = {}
    for style in ff.get_styles(AtomStyle):
        for at in style.get_types(AtomType):
            if at.name not in seen:
                seen[at.name] = at
    return list(seen.values())


def _atom_name_map(atomistic: Atomistic) -> dict[int, str]:
    """Assign unique moltemplate ``$atom:`` ids to every atom.

    Always emits ``a<index>``-style names so no two atoms collide even
    when the underlying ``name`` attribute repeats (e.g. multiple water
    molecules each with ``O``/``H1``/``H2``).
    """
    out: dict[int, str] = {}
    for idx, atom in enumerate(atomistic.atoms, start=1):
        out[id(atom)] = f"a{idx}"
    return out


def _sanitise_id(s: str) -> str:
    """Make ``s`` a safe moltemplate ``$atom:`` identifier."""
    out = []
    for ch in s:
        if ch.isalnum() or ch in "_./":
            out.append(ch)
        else:
            out.append("_")
    result = "".join(out)
    return result or "x"


def _fmt(v: float) -> str:
    """Format floats compactly but unambiguously."""
    try:
        f = float(v)
    except (TypeError, ValueError):
        return str(v)
    if abs(f) >= 1e7 or (f != 0.0 and abs(f) < 1e-4):
        return f"{f:.6e}"
    return f"{f:g}"
